### ISSUE TITLE
Wrong GWT version is occasionally added to a project

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#343]
**Reported by Artur Signell on 16 Dec 2010 13:58 UTC**
When updating a project from 6.4.8 to 6.5.0.pre1 it sometimes happens that the GWT version is not updated to 2.1.0, causing compilation errors when compiling the widgetset.

Migrated-From: https://dev.vaadin.com/ticket/6169

**Comment by makoivis** [comment]
**Comment by Henri Sara on 17 Dec 2010 09:01 UTC**
Fixed in [and [16555](16554]), reviewed by Artur Signell.

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
