### ISSUE TITLE
Vaadin Eclipse plug-in does not work with IvyDE 2.2.0.final

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#578]
**Reported by Artur Signell on 3 Dec 2013 07:50 UTC**
According to https://vaadin.com/forum#!/thread/4459919 you get 

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/ivyde/eclipse/cpcontainer/IvyClasspathContainer
```

when creating a new project.

Migrated-From: http://dev.vaadin.com//ticket/13022

**Comment by makoivis** [comment]
**Modified by Artur Signell on 3 Dec 2013 07:51 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 3 Dec 2013 13:25 UTC**

**Comment by makoivis** [comment]
**Comment by Henri Sara on 3 Dec 2013 13:52 UTC**
The API of IvyDE has changed somewhat between 2.2.0.beta and 2.2.0.final (classpath containers are now in a different package and with separate interface and implementation, some internal API has been removed/replaced).

**Comment by makoivis** [comment]
**Comment by Henri Sara on 9 Dec 2013 08:12 UTC**
Fixed in plug-in 2.2.0.201312...

Note that the new version is NOT compatible with IvyDE 2.2.0.beta1

**Comment by makoivis** [comment]
**Modified by Artur Signell on 12 May 2014 07:41 UTC**

**Comment by makoivis** [comment]
**Modified by Artur Signell on 9 Sep 2014 08:39 UTC**
